# Generated by Django 6.0.1 on 2026-02-07 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_date', models.DateField(db_index=True)),
                ('rg_number', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice Receipts',
                'ordering': ['rg_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'rg_number'), name='unique_invoice_receipt_per_user')],
            },
        ),
        migrations.CreateModel(
            name='OutgoingInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_date', models.DateField(db_index=True)),
                ('rg_number', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.CharField(max_length=255)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Outgoing Invoices',
                'ordering': ['rg_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'rg_number'), name='unique_outgoing_invoice_per_user')],
            },
        ),
    ]
