# Generated by Django 6.0.1 on 2026-02-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripbook',
            old_name='destination',
            new_name='destinationAddress',
        ),
    ]
