# Generated by Django 6.0.1 on 2026-02-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripbook', '0002_rename_destination_tripbook_destinationaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
